@startuml RemarkParserClassDiagram
hide circle
skinparam classAttributeIconSize 0

title Remark Parser Class Diagram

class "<<interface>>\nParser" as Parser
class RemarkCommandParser {
  +parse(): RemarkCommand
}
class ParserException

RemarkCommandParser .up.|> Parser
Parser .right.> ParserException : throws
RemarkCommandParser .right.> ParserException : throws
@enduml
