@startuml RemarkCommandClassDiagram
hide circle
skinparam classAttributeIconSize 0

title Remark Command Class Diagram

class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
class RemarkCommand {
  +COMMAND_WORD: String
  +MESSAGE_USAGE: String
  +MESSAGE_NOT_IMPLEMENTED_YET: String
  +execute(Model): CommandResult
}
class CommandException

RemarkCommand -up-|> Command
Command ..> CommandException : throws
RemarkCommand .right.> CommandException : throws
@enduml
