@startuml CommitActivityDiagram
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

title Commit Activity Diagram
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if (command commits AddressBook?) then ([Yes])
    :Purge redundant states;
    :Save AddressBook to
    addressBookStateList;
else ([No])
endif
stop
@enduml
