@startuml ParserClasses
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

title Parser Classes

class "{abstract}\nCommand" as Command
class XYZCommand
class AddTransactionCommand

package "Parser Classes" {
class "<<interface>>\nParser" as Parser
class AddressBookParser
class XYZCommandParser
class AddTransactionCommandParser
class CliSyntax
class ParserUtil
class ArgumentMultimap
class ArgumentTokenizer
class Prefix
}

class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> XYZCommandParser: <<create>>
AddressBookParser .down.> AddTransactionCommandParser: <<create>>

XYZCommandParser ..> XYZCommand : <<create>>
AddTransactionCommandParser ..> AddTransactionCommand : <<create>>
AddressBookParser ..> Command : <<use>>
XYZCommandParser .up.|> Parser
AddTransactionCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
AddTransactionCommand -up-|> Command

note bottom of AddTransactionCommandParser
  AddTransactionCommandParser is a concrete example of a
  command-specific parser (e.g., for `addtxn`).
end note
@enduml
