@startuml LogicSequenceDiagramTracing
!include ../style.puml

title Logic Sequence Diagram (Tracing)

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create ecp
abp -> ecp : new EditCommandParser()
abp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: new EditCommand(index, editPersonDescriptor)
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command

@enduml
